spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: ef62628a-6767-40fe-abb0-8fa22ca6c447.pub.cloud.scaleway.com:9092
          #brokers: localhost:9092
      bindings:
        customers-in:
          destination: customers-in
          contentType: application/json
        customers-out:
          destination: customers-out
          contentType: application/json
