spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        customers-in:
          destination: customers
          contentType: application/json
        customers-out:
          destination: customers
          contentType: application/json